"""Alter inventory table to add a right primary key.

Revision ID: 1d9b69f7075f
Revises: cf4a1d730db6
Create Date: 2025-04-18 16:27:02.366938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9b69f7075f'
down_revision: Union[str, None] = 'cf4a1d730db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'id')
    # ### end Alembic commands ###
