version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_catalogue
    ports:
      - "27017:27017" # MongoDB exposé en local
    environment:
      MONGO_INITDB_DATABASE: catalogue_db # BDD appelée "catalogue_db"
    volumes:
      - mongo_data:/data/db

  catalogue-api:
    build: . # Dockerfile local
    container_name: catalogue_api
    ports:
      - "8081:8081" # Expose Express en local
    environment:
      - MONGO_URL=mongodb://mongo:27017/catalogue_db # URL Mongo pour ton app
    depends_on:
      - mongo # Lance Express après Mongo

volumes:
  mongo_data: